# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import videos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='thumbnail_url',
        ),
        migrations.RemoveField(
            model_name='video',
            name='url',
        ),
        migrations.AddField(
            model_name='video',
            name='content',
            field=models.FileField(default=None, upload_to='videos', validators=[videos.validators.validate_video_file]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to='thumbnails'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='sites.Site'),
        ),
    ]
