# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-13 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import videos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20160512_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='content',
            field=models.FileField(upload_to='videos', validators=[videos.validators.validate_video_file]),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnails'),
        ),
    ]
