# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-27 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_add_listing_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
