# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
