# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='premium_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='info',
            name='price_month',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='info',
            name='price_year',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='info',
            name='stripe_public_key',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='stripe_secret_key',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='stripe_user_id',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
