# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0004_added_payments_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='premium_enabled',
            field=models.BooleanField(default=False, help_text='Videos that are marked premium will force users to subscribe before being able to view them.', verbose_name='Premium Enabled'),
        ),
        migrations.AlterField(
            model_name='info',
            name='price_month',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Users will charged this amount per month for premium access.', max_digits=6, verbose_name='Monthly Price'),
        ),
        migrations.AlterField(
            model_name='info',
            name='price_year',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Users will charged this amount per month for premium access.', max_digits=6, verbose_name='Annual Price'),
        ),
    ]
