# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 23:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0004_added_payments_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='premium_enabled',
        ),
        migrations.RemoveField(
            model_name='info',
            name='price_month',
        ),
        migrations.RemoveField(
            model_name='info',
            name='price_year',
        ),
        migrations.RemoveField(
            model_name='info',
            name='stripe_public_key',
        ),
        migrations.RemoveField(
            model_name='info',
            name='stripe_secret_key',
        ),
        migrations.RemoveField(
            model_name='info',
            name='stripe_user_id',
        ),
    ]
