# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0005_remove_payment_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='header',
            field=models.TextField(default='Start Learning Now'),
        ),
        migrations.AddField(
            model_name='info',
            name='logo',
            field=models.ImageField(null=True, upload_to='logos'),
        ),
        migrations.AddField(
            model_name='info',
            name='main_bg_color',
            field=models.TextField(default='#666'),
        ),
        migrations.AddField(
            model_name='info',
            name='main_color',
            field=models.TextField(default='#fff'),
        ),
        migrations.AddField(
            model_name='info',
            name='nav_bg_color',
            field=models.TextField(default='#666'),
        ),
        migrations.AddField(
            model_name='info',
            name='nav_color',
            field=models.TextField(default='#fff'),
        ),
        migrations.AddField(
            model_name='info',
            name='sub_header',
            field=models.TextField(default="We're the go-to source of tutorials on the web"),
        ),
    ]
