# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0006_auto_20160601_0444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='nav_bg_color',
        ),
        migrations.RemoveField(
            model_name='info',
            name='nav_color',
        ),
        migrations.AddField(
            model_name='info',
            name='subscribe_pitch',
            field=models.TextField(default='Be part of a revolution'),
        ),
    ]
