# RENAME THIS FILE TO local_settings.py

# MAKE SURE TO CHANGE THESE VALUES!!!
STRIPE_CLIENT_ID = 'ca_32D88BD1qLklliziD7gYQvctJIhWBSQ7'
STRIPE_CLIENT_SECRET = 'pk_test_6pRNASCoBOKtIshFeQd4XMUh'
AZURE_ACCOUNT_NAME = ''
AZURE_ACCOUNT_KEY = ''
