# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 17:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sites.Site')),
                ('premium_enabled', models.BooleanField(default=False, help_text='Videos that are marked premium will force users to subscribe before being able to view them.', verbose_name='Premium Enabled')),
                ('price_month', models.DecimalField(decimal_places=2, default=0.0, help_text='Users will charged this amount per month for premium access.', max_digits=6, verbose_name='Monthly Price')),
                ('price_year', models.DecimalField(decimal_places=2, default=0.0, help_text='Users will charged this amount per month for premium access.', max_digits=6, verbose_name='Annual Price')),
                ('stripe_public_key', models.CharField(max_length=32, null=True)),
                ('stripe_secret_key', models.CharField(max_length=32, null=True)),
                ('stripe_user_id', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=64, verbose_name='Customer ID')),
                ('active_until', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
