# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 05:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='series',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series', to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='series',
            name='thumbnail_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
